name: zipcode-lib
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - CHANGELOG.md

env:
  GIT_LOGIN: ${{ secrets.GIT_LOGIN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  VERSION_FILE: build.gradle
  VERSION_EXTRACT_PATTERN: '\d'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      #Prepare
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      #Verify integrity
      - name: Build with Gradle
        run: ./gradlew compileJava

      #Create a Jar file
      - name: Create Jar
        run: ./gradlew assemble

      #Running tests
      - name: Running test
        run: ./gradlew test

      #Publish a package to Artifact registrys
      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
